### ISSUE TITLE
CP Error after install

### ISSUE THREAD

**Issue by DesignByNeil** [silentzco/statamic-mailchimp#62]
Hi Erin

Just trying to get the addon setup and I have followed the [readme](https://github.com/silentzco/statamic-mailchimp/blob/main/README.md) install and added the API key but i am getting the following error.

```
Symfony\Component\Routing\Exception\RouteNotFoundException
Route [statamic.cp.mailchimp.config.edit] not defined. (View: /home/ploi/my-site.dev/vendor/statamic/cms/resources/views/layout.blade.php)
```
`throw new RouteNotFoundException("Route [{$name}] not defined.");`

Not sure if i have missed something else that i need to setup.

I am running Statamic v3.0.46 & php 8

Thanks

**Comment by edalzell** [comment]
When are you getting that error? What are you trying to do?

**Comment by DesignByNeil** [comment]
It happens when i try to hit the cp after install

**Comment by edalzell** [comment]
I can't reproduce with the latest version of Mailchimp (and Forma). I pushed an update to Forma that might have been causing this, can you please run `composer update` and see if this issue goes away?

**Comment by DesignByNeil** [comment]
Still getting the issue. I haven't installed Forma. Is it required? Perhaps that is what is causing the issue. After install i haven't been able to view any part of the cp.

**Comment by DesignByNeil** [comment]
I have been able to install the addon locally using valet and php 7.4 however it still wont allow access to the cp when I add the changes through to my server which is setup with Ploi and DO and php 8.0.1.

**Comment by edalzell** [comment]
> Still getting the issue. I haven't installed Forma. Is it required? Perhaps that is what is causing the issue. After install i haven't been able to view any part of the cp.

Forma is a dependency of Mailchimp, so would get updated when you ran `composer update`

**Comment by edalzell** [comment]
> I have been able to install the addon locally using valet and php 7.4 however it still wont allow access to the cp when I add the changes through to my server which is setup with Ploi and DO and php 8.0.1.

So it works locally (you can access the CP) but not on your prod server? And the only major difference is the PHP version?

**Comment by edalzell** [comment]
I tried Mailchimp on a local PHP 8 install and it seems to work fine.

> I add the changes through to my server

@DesignByNeil what do you mean by that?

**Comment by DesignByNeil** [comment]
I reversed the changes and removed the addon and I could 

> > I have been able to install the addon locally using valet and php 7.4 however it still wont allow access to the cp when I add the changes through to my server which is setup with Ploi and DO and php 8.0.1.
> 
> So it works locally (you can access the CP) but not on your prod server? And the only major difference is the PHP version?

Yes thats correct. I had purchased a license for it too so it shouldn't be anything to do with that.

**Comment by DesignByNeil** [comment]
> I tried Mailchimp on a local PHP 8 install and it seems to work fine.
> 
> > I add the changes through to my server
> 
> @DesignByNeil what do you mean by that?

I pushed the local changes to my git repo and then updated the prod server but i then couldn't access the cp.

**Comment by DesignByNeil** [comment]
I have rolled back the php version on the prod server to 7.4 and still getting the issue on install. So that rules out the php version.

**Comment by DesignByNeil** [comment]
Running `php artisan route:clear` resolved the issue

**Comment by edalzell** [comment]
> Running `php artisan route:clear` resolved the issue

oh interesting, your routes were cached but the correct ones weren't in there.

**Comment by DanielDarrenJones** [comment]
@edalzell I'm also now hitting this issue, when I cache my route the plugin gives a 500 error on the CP. Clearing the route cache fixes this again though

**Comment by edalzell** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/6069653?u=b0a63982530a2fd2aa037031f64dcf59e11c651a&amp;v=4&amp;size=80">@edalzell](https://github.com/edalzell?rgh-link-date=2025-02-24T16%3A49%3A08.000Z) I'm also now hitting this issue, when I cache my route the plugin gives a 500 error on the CP. Clearing the route cache fixes this again though

This is quite old, can you please open a new issue with all the relevant details?
